Power.create([
  { code: '1', name: 'Agility' },
  { code: '2', name: 'Accelerated Healing' },
  { code: '3', name: 'Lantern Power Ring' },
  { code: '4', name: 'Dimensional Awareness' },
  { code: '5', name: 'Cold Resistance' },
  { code: '6', name: 'Durability' },
  { code: '7', name: 'Stealth' },
  { code: '8', name: 'Energy Absorption' },
  { code: '9', name: 'Flight' },
  { code: '10', name: 'Danger Sense' },
  { code: '11', name: 'Underwater breathing' },
  { code: '12', name: 'Marksmanship' },
  { code: '13', name: 'Weapons Master' },
  { code: '14', name: 'Power Augmentation' },
  { code: '15', name: 'Animal Attributes' },
  { code: '16', name: 'Longevity' },
  { code: '17', name: 'Intelligence' },
  { code: '18', name: 'Super Strength' },
  { code: '19', name: 'Cryokinesis' },
  { code: '20', name: 'Telepathy' },
  { code: '21', name: 'Energy Armor' },
  { code: '22', name: 'Energy Blasts' },
  { code: '23', name: 'Duplication' },
  { code: '24', name: 'Size Changing' },
  { code: '25', name: 'Density Control' },
  { code: '26', name: 'Stamina' },
  { code: '27', name: 'Astral Travel' },
  { code: '28', name: 'Audio Control' },
  { code: '29', name: 'Dexterity' },
  { code: '30', name: 'Omnitrix' },
  { code: '31', name: 'Super Speed' },
  { code: '32', name: 'Possession' },
  { code: '33', name: 'Animal Oriented Powers' },
  { code: '34', name: 'Weapon-based Powers' },
  { code: '35', name: 'Electrokinesis' },
  { code: '36', name: 'Darkforce Manipulation' },
  { code: '37', name: 'Death Touch' },
  { code: '38', name: 'Teleportation' },
  { code: '39', name: 'Enhanced Senses' },
  { code: '40', name: 'Telekinesis' },
  { code: '41', name: 'Energy Beams' },
  { code: '42', name: 'Magic' },
  { code: '43', name: 'Hyperkinesis' },
  { code: '44', name: 'Jump' },
  { code: '45', name: 'Clairvoyance' },
  { code: '46', name: 'Dimensional Travel' },
  { code: '47', name: 'Power Sense' },
  { code: '48', name: 'Shapeshifting' },
  { code: '49', name: 'Peak Human Condition' },
  { code: '50', name: 'Immortality' },
  { code: '51', name: 'Camouflage' },
  { code: '52', name: 'Element Control' },
  { code: '53', name: 'Phasing' },
  { code: '54', name: 'Astral Projection' },
  { code: '55', name: 'Electrical Transport' },
  { code: '56', name: 'Fire Control' },
  { code: '57', name: 'Projection' },
  { code: '58', name: 'Summoning' },
  { code: '59', name: 'Enhanced Memory' },
  { code: '60', name: 'Reflexes' },
  { code: '61', name: 'Invulnerability' },
  { code: '62', name: 'Energy Constructs' },
  { code: '63', name: 'Force Fields' },
  { code: '64', name: 'Self-Sustenance' },
  { code: '65', name: 'Anti-Gravity' },
  { code: '66', name: 'Empathy' },
  { code: '67', name: 'Power Nullifier' },
  { code: '68', name: 'Radiation Control' },
  { code: '69', name: 'Psionic Powers' },
  { code: '70', name: 'Elasticity' },
  { code: '71', name: 'Substance Secretion' },
  { code: '72', name: 'Elemental Transmogrification' },
  { code: '73', name: 'Technopath/Cyberpath' },
  { code: '74', name: 'Photographic Reflexes' },
  { code: '75', name: 'Seismic Power' },
  { code: '76', name: 'Animation' },
  { code: '77', name: 'Precognition' },
  { code: '78', name: 'Mind Control' },
  { code: '79', name: 'Fire Resistance' },
  { code: '80', name: 'Power Absorption' },
  { code: '81', name: 'Enhanced Hearing' },
  { code: '82', name: 'Nova Force' },
  { code: '83', name: 'Insanity' },
  { code: '84', name: 'Hypnokinesis' },
  { code: '85', name: 'Animal Control' },
  { code: '86', name: 'Natural Armor' },
  { code: '87', name: 'Intangibility' },
  { code: '88', name: 'Enhanced Sight' },
  { code: '89', name: 'Molecular Manipulation' },
  { code: '90', name: 'Heat Generation' },
  { code: '91', name: 'Adaptation' },
  { code: '92', name: 'Gliding' },
  { code: '93', name: 'Power Suit' },
  { code: '94', name: 'Mind Blast' },
  { code: '95', name: 'Probability Manipulation' },
  { code: '96', name: 'Gravity Control' },
  { code: '97', name: 'Regeneration' },
  { code: '98', name: 'Light Control' },
  { code: '99', name: 'Echolocation' },
  { code: '100', name: 'Levitation' },
  { code: '101', name: 'Toxin and Disease Control' },
  { code: '102', name: 'Banish' },
  { code: '103', name: 'Energy Manipulation' },
  { code: '104', name: 'Heat Resistance' },
  { code: '105', name: 'Natural Weapons' },
  { code: '106', name: 'Time Travel' },
  { code: '107', name: 'Enhanced Smell' },
  { code: '108', name: 'Illusions' },
  { code: '109', name: 'Thirstokinesis' },
  { code: '110', name: 'Hair Manipulation' },
  { code: '111', name: 'Illumination' },
  { code: '112', name: 'Omnipotent' },
  { code: '113', name: 'Cloaking' },
  { code: '114', name: 'Changing Armor' },
  { code: '115', name: 'Power Cosmic' },
  { code: '116', name: 'Biokinesis' },
  { code: '117', name: 'Water Control' },
  { code: '118', name: 'Radiation Immunity' },
  { code: '119', name: 'Vision - Telescopic' },
  { code: '120', name: 'Toxin and Disease Resistance' },
  { code: '121', name: 'Spatial Awareness' },
  { code: '122', name: 'Energy Resistance' },
  { code: '123', name: 'Telepathy Resistance' },
  { code: '124', name: 'Molecular Combustion' },
  { code: '125', name: 'Omnilingualism' },
  { code: '126', name: 'Portal Creation' },
  { code: '127', name: 'Magnetism' },
  { code: '128', name: 'Mind Control Resistance' },
  { code: '129', name: 'Plant Control' },
  { code: '130', name: 'Sonar' },
  { code: '131', name: 'Sonic Scream' },
  { code: '132', name: 'Time Manipulation' },
  { code: '133', name: 'Enhanced Touch' },
  { code: '134', name: 'Magic Resistance' },
  { code: '135', name: 'Invisibility' },
  { code: '136', name: 'Sub-Mariner' },
  { code: '137', name: 'Radiation Absorption' },
  { code: '138', name: 'Intuitive aptitude' },
  { code: '139', name: 'Vision - Microscopic' },
  { code: '140', name: 'Melting' },
  { code: '141', name: 'Wind Control' },
  { code: '142', name: 'Super Breath' },
  { code: '143', name: 'Wallcrawling' },
  { code: '144', name: 'Vision - Night' },
  { code: '145', name: 'Vision - Infrared' },
  { code: '146', name: 'Grim Reaping' },
  { code: '147', name: 'Matter Absorption' },
  { code: '148', name: 'The Force' },
  { code: '149', name: 'Resurrection' },
  { code: '150', name: 'Terrakinesis' },
  { code: '151', name: 'Vision - Heat' },
  { code: '152', name: 'Vitakinesis' },
  { code: '153', name: 'Radar Sense' },
  { code: '154', name: 'Qwardian Power Ring' },
  { code: '155', name: 'Weather Control' },
  { code: '156', name: 'Vision - X-Ray' },
  { code: '157', name: 'Vision - Thermal' },
  { code: '158', name: 'Web Creation' },
  { code: '159', name: 'Reality Warping' },
  { code: '160', name: 'Odin Force' },
  { code: '161', name: 'Symbiote Costume' },
  { code: '162', name: 'Speed Force' },
  { code: '163', name: 'Phoenix Force' },
  { code: '164', name: 'Molecular Dissipation' },
  { code: '165', name: 'Vision - Cryo' },
  { code: '166', name: 'Omnipresent' },
  { code: '167', name: 'Omniscient' }
])

Race.create([
  { code: '1', name: 'Undefined' },
  { code: '2', name: 'Alien' },
  { code: '3', name: 'Alpha' },
  { code: '4', name: 'Amazon' },
  { code: '5', name: 'Android' },
  { code: '6', name: 'Animal' },
  { code: '7', name: 'Asgardian' },
  { code: '8', name: 'Atlantean' },
  { code: '9', name: 'Bizarro' },
  { code: '10', name: 'Bolovaxian' },
  { code: '11', name: 'Clone' },
  { code: '12', name: 'Cosmic Entity' },
  { code: '13', name: 'Cyborg' },
  { code: '14', name: 'Czarnian' },
  { code: '15', name: 'Dathomirian Zabrak' },
  { code: '16', name: 'Demi-God' },
  { code: '17', name: 'Demon' },
  { code: '18', name: 'Eternal' },
  { code: '19', name: 'Flora Colossus' },
  { code: '20', name: 'Frost Giant' },
  { code: '21', name: 'God / Eternal' },
  { code: '22', name: 'Gorilla' },
  { code: '23', name: 'Gungan' },
  { code: '24', name: 'Human' },
  { code: '25', name: 'Human / Altered' },
  { code: '26', name: 'Human / Clone' },
  { code: '27', name: 'Human / Cosmic' },
  { code: '28', name: 'Human / Radiation' },
  { code: '29', name: 'Human-Kree' },
  { code: '30', name: 'Human-Spartoi' },
  { code: '31', name: 'Human-Vulcan' },
  { code: '32', name: 'Human-Vuldarian' },
  { code: '33', name: 'Icthyo Sapien' },
  { code: '34', name: 'Inhuman' },
  { code: '35', name: 'Kakarantharaian' },
  { code: '36', name: 'Korugaran' },
  { code: '37', name: 'Kryptonian' },
  { code: '38', name: 'Luphomoid' },
  { code: '39', name: 'Maiar' },
  { code: '40', name: 'Martian' },
  { code: '41', name: 'Metahuman' },
  { code: '42', name: 'Mutant' },
  { code: '43', name: 'Mutant / Clone' },
  { code: '44', name: 'New God' },
  { code: '45', name: 'Neyaphem' },
  { code: '46', name: 'Parademon' },
  { code: '47', name: 'Planet' },
  { code: '48', name: 'Rodian' },
  { code: '49', name: 'Saiyan' },
  { code: '50', name: 'Spartoi' },
  { code: '51', name: 'Strontian' },
  { code: '52', name: 'Symbiote' },
  { code: '53', name: 'Talokite' },
  { code: '54', name: 'Tamaranean' },
  { code: '55', name: 'Ungaran' },
  { code: '56', name: 'Vampire' },
  { code: '57', name: 'Xenomorph XX121' },
  { code: '58', name: 'Yautja' },
  { code: '59', name: 'Yoda'' species' },
  { code: '60', name: 'Zen-Whoberian' },
  { code: '61', name: 'Zombie' }
])

Gender.create([
  { name: 'Male', code: '1' },
  { name: 'Female', code: '2' },
  { name: 'N/A', code: '3' }
])
